### ISSUE TITLE
Smooth rotation animation of vehicle marker

### ISSUE THREAD

**Issue by dasirahul7** [MindorksOpenSource/Uber-Car-Animation-Android#1]
First of all Thank you so much for this excellent example.
Actually I'm facing glitch or vibrating marker on map while moving, It's not showing as your gif image.

Can you please share with me smooth rotation marker example on google map.

Thank you!

**Comment by deeprathod** [comment]
@dasirahul7  Did you find any solution to this? Same here. facing the same issue. The car is flickering too much while navigating.

**Comment by ishdemon** [comment]
We don't need getRotation method as MapUtility library already has it.
Just add `implementation 'com.google.maps.android:maps-utils-ktx:3.2.0'`
And Use this to avoid flickering : 
`val rotation = SphericalUtil.computeHeading(previousLatLng!!,currentLatLng)`
I have created a PR :
https://github.com/MindorksOpenSource/Uber-Car-Animation-Android/pull/2

**Comment by dasirahul7** [comment]
> We don't need getRotation method as MapUtility library already has it.
> Just add `implementation 'com.google.maps.android:maps-utils-ktx:3.2.0'`
> And Use this to avoid flickering :
> `val rotation = SphericalUtil.computeHeading(previousLatLng!!,currentLatLng)`
> I have created a PR :
> #2

Yes I got it, Thank you so much for the reply!
